engines:
    eslint:
        enabled: true
        checks:
            complexity:
                enabled: false
    fixme:
        enabled: true

ratings:
    paths:
        - "src/js/scrollbox.js"

exclude_paths:
    - dist/
    - tests/
    - Gruntfile.js