language: node_js

node_js:
    - '4'
    - '5'

script:
    - grunt ci

env:
    global:
        - secure: Uf5Ze0mInPTw/ti5TbTsMROdPkC7yWs0Ebg7czU+j34GGZTgsBUNHqkwZAowEflfV6tdQywqONlReEF9s948nXc8aRwcdKanyW0jZL+kH8GuXegMe4DpbFUS/zdkzpGsY9qlF/YTwl+XMol+HsiR9cfg1y8aj9lENEuSqthhM/jXSLmc+cm3jLKkmSh06MUQehqCC7ACXProXcfgRngjw88NAOt7f7cSb4k2SybzOwoibO3NolhQB691+TFoYKYtK8aPQFaIsbrz6lAa17VaKpHb1mvTnt11UYePCGGJRfT7KKfka/ryVveXcZ0WvHLMV8Eee4WBLt68XC+NpH3S+71MQjCATH2qMD8ZuHgpaNc5iW/LGAtco10C8jKpzAZCp2UXjr5WZDWUrwOEsSLGWyzCe3VSXDg+piIRUZDKAMWQyaZpQ5LiJlEwk8HIyI4mWyPAVTbOjTeBghsAcztfYml8g7OK/0qsqpaffkq4eNih0Vz2rQheSrRDmngeInZEL81tcMhyAgyUiJpHYCgOSMA6XFcl87IkNiMf/XCFWY77sNzfdKU3S1GmU+34lf8fjnzPdUW8lnrHtuGZtw2g710S9VRYqOI3JL38uBYhbtZWNnLeSNYPbE0uQyO630NuyAluhtP/AHtsgbojy3KlG33keypmpwI5g+9pV43IglI=
        - secure: TqjcNzlMR4ULt3g04MAqqLu+5x2hpPXfNV/ABY7emYW1O0ru5Z9QvBg1uZqhMILSqDpOrm5S46rAUS5RbzpVpYSYToi1+ZfNC8jSskBB5AzL6byy0WGnbs7NvRI9bHlUptRk7vTfUuop2M7PwfKPEKKYQveWTGbQuBGbUOdPgaKCi7KYvAfo7z7dQID4Bt3HkCWsnJH8Xp9F5k37p+WKenU6p4lBX5gQo3DwU2JB8jYvNsJqVlGJsVO2t0g4mU31hMTmWjVVrSD/2tmqchg9GmxLKbHS2QS9nzDjmF9xeD15K6PqPaghLbdf8xEAAoyDeM9SmYF0V2ZS6D8lSy06v1qs3PfMwLf2vJ+548D0WBXfqaXwOVLUxOzLnML2vBaZoVpiG1nrF5JaHz/D1I29VSg6Bb23hQ8qhXqiVvpTeCo3IXCDtF/U2FOK95YlU5DgmDwtLkkKQtL9mv7rdLb6+ziYB1hAcBk0bi9Zf+OFRV2wda2ruxHyTCQwpChyVazuPftGPp23+K2X/NwnL20opxlFGS9KCmcRH5JAkjPSzXkpv07ZtmsjtMAgjV76M4rzxjsYcbuC7nCr328umKnD/fSEEaSU5my6m7XXp4Ts5iTh/2EgHrN0CKFaPOT/SkTfDWsecgKe/GTjeNgRv+YXx1le13Jkic4oDJnM7PXNOCA=
