language: node_js

node_js:
    - '5'

script:
    - grunt ci

env:
    global:
        - secure: MSPat1QJZTLTdDdY3OfyUl7j++L+gm0OZE40n1zDakLNTtFUlQti3ZT8IFapDtaqCup1vgic7xeRxi5dsoEy6/2XRVb02c1ShO0SdQOmvMatqy/OmXsVm0h/IpRWh9aP3jGW+Wh7+Yk418je0t7bXfyqc7rmoKupGFaMexkDMt1HtZ62bormZTHFoQ4CdWhTHbAc1jPKIlbFh2JI9KxCITJaBusf1kUf87bK9oZev0CMLHs/pwRu36WoeWqI11XNoeNDwrajAIjs6G/GKu2FKqUJxxT5sh5XUov3XQctvDKNNWIVos//9k21n0wsPkK9kqB1GqaUWVPPhyBVYfuhO6pIU+b0cGMiCQYMdyzTUHrd9h+kBniA/CKh47UtRc/utmy0pzBv7ab2jb7cgq8WhEoRDOlo6iYmzAoJD86R0rjHx2z1+Q4Q/jVWGQqJbmwrrnBGzt6TGCR+do4doHN3CjBdnODVxZnN2JPyWlyB63sNnGZyBjYpEXL54E0a4/O5SdN0+Owg1twlvIRE9fJ0T/FY3wmqU1PTLlffGDUau8h0yWRXQy1GtWerQ4kdV6kVJd8Giyopw2bpr5OwpY7XV3JsbVdURMVJf5HfJpj/ZVEbxb8zgxMDuTNk4lkYyPn7flxP4VoNW46fJYJ+rxJ3rXopvIAhwRyCNVn8cYgCvEI=
        - secure: B+Ekiq1s1+0T32dCQta1YbwHFKv6FqBfVhZQFW5dvuIlqsazi+rxjI0dBlqrvicj5ZjdHJT/ihk4Ka+AjSwB8Z8wXOWbb2vKtXuLLa/rhnKfabCKW/LOIs8TM2zXnNNen5n4DyX0AA5kwUXh/YOWFU7Ow0ZHh1KYA8FOj4UYYv35BMlDYznbr8Y3K2eTzUOWeHK8CETDcl+ygALW9fRW3ZrCvrPEnc9ZehE+xWHou1OThpH0qt5aGYs/yyj9kbVxGBA9Y/CazZ5KkE29Ur2+NQ1uX/oUNdsaMMpckdqpgV+AqfmCQHKMAIL5mqjBPWN6+oCgMnLphwXrADId3ybhVnhfSIu/mLC9Td+3E7By/OZntmPsrzYubVjAr6TTdAirPAb3k0UNll4T32738B93ZJ9OOqd2MCW4VZyi2xY5e927dJLJw8wvkJpTQy6J4ujsKv2waNap9NsuEaqOjxgd/FmdOcXJ90W2CA2RTs6ZdTINy/wDv8CgDja500TQU3/akjkH4hxy/JSgaZigdPyl4xyLk647ZcoOt7If+vYgXf3i9Hz8wtZq9hlyZpfgvEv+xmlVvuuDT1FVx/2kJbQnmWa8QjneCRMP4mK5UT54lPjx5HVo3BzaYKTur60amh2RzCoX12dB+cZ2j6OxZFkyIxQ4Lausxb66MujxBsyqSss=
